# Generated by Django 5.2 on 2025-04-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='employee_id',
            field=models.CharField(default='EMP-00000', max_length=20, unique=True),
        ),
    ]
