# Generated by Django 5.2 on 2025-04-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customeruser_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
