# Generated by Django 5.2 on 2025-04-22 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('base_salary', models.FloatField()),
                ('attendance_pay', models.FloatField()),
                ('bonuses', models.FloatField(default=0)),
                ('overtime_pay', models.FloatField(default=0)),
                ('deductions', models.FloatField(default=0)),
                ('leave_deductions', models.FloatField(default=0)),
                ('net_salary', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='employee_management.employee')),
            ],
        ),
    ]
