# Generated by Django 5.2 on 2025-04-22 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='end_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='start_date',
            new_name='to_date',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('earned', 'Earned Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
